/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#b8a3ff",
        "on-tertiary": "#25006b",
        "outline-variant": "#434855",
        "primary-fixed-dim": "#5a90ff",
        "error": "#ff716c",
        "on-error-container": "#ffa8a3",
        "secondary-container": "#006875",
        "on-primary-fixed": "#000000",
        "surface-variant": "#1f2636",
        "primary-fixed": "#739eff",
        "inverse-on-surface": "#505562",
        "error-container": "#9f0519",
        "inverse-surface": "#faf9ff",
        "on-secondary-fixed": "#003a42",
        "tertiary-container": "#7c4dff",
        "primary-dim": "#0f6df3",
        "tertiary-dim": "#7e51ff",
        "on-tertiary-fixed": "#1c0055",
        "primary-container": "#739eff",
        "on-secondary-container": "#e8fbff",
        "inverse-primary": "#0059cb",
        "background": "#090e19",
        "on-surface": "#e7eafb",
        "on-primary-fixed-variant": "#002966",
        "surface-container-low": "#0e131f",
        "tertiary": "#a68cff",
        "on-tertiary-container": "#ffffff",
        "surface-tint": "#89acff",
        "surface-bright": "#242c3d",
        "outline": "#717583",
        "primary": "#89acff",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#1f2636",
        "surface-container-high": "#191f2e",
        "on-error": "#490006",
        "secondary-fixed": "#26e6ff",
        "on-primary-container": "#002053",
        "on-background": "#e7eafb",
        "surface-dim": "#090e19",
        "surface-container": "#131927",
        "secondary-dim": "#00d4ec",
        "error-dim": "#d7383b",
        "on-primary": "#002b6a",
        "secondary-fixed-dim": "#00d7f0",
        "tertiary-fixed-dim": "#ab93ff",
        "on-tertiary-fixed-variant": "#4000ad",
        "on-secondary-fixed-variant": "#005964",
        "secondary": "#00e3fd",
        "surface": "#090e19",
        "on-surface-variant": "#a6abba",
        "on-secondary": "#004d57"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "sans": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
